stages:
  foo:
    cmd: python checkpoint.py
    params:
    - start
    - checkpoint.py:
      - STEP
    deps:
    - checkpoint.py
    - bar
    outs:
    - foo:
        checkpoint: true
    live:
      dvclive:
        summary: true
        html: true
