stages:
  foo:
    cmd: python checkpoint.py
    params:
    - start
    - checkpoint.py:
      - STEP
    deps:
    - checkpoint.py
    - bar
    outs:
    - foo:
        checkpoint: true
    metrics:
    - scores.yaml:
        cache: false
    live:
      logs:
        summary: true
        html: true
