stages:
  foo:
    cmd: python checkpoint.py
    params:
    - start
    deps:
    - checkpoint.py
    - bar
    outs:
    - foo:
        checkpoint: true
    metrics:
    - scores.yaml:
        cache: false
